site_name: Birdee Language
#theme: readthedocs
#pages:
#  - 'Birdee Language' : index.md
#  - 'Birdee playground (REPL)' : Birdee-playground-(REPL).md
#  - 'Compiler command line mannual' : Compiler-command-line-mannual.md
#  - 'Using automatic building tool' : bbuild.md
#  - 